// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.5.1")]
    public sealed partial class migwritertitle_add : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(migwritertitle_add));
        
        string IMigrationMetadata.Id
        {
            get { return "202504131803417_mig-writertitle_add"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
